Repository MIT-Emerging-Talent/ET6-CDSP-group-06-repo, pull requests merged in 2025-06, with the labels that each got.

#8 Add group norms and summary for Milestone 0
  collaboration/README.md
Labels: documentation

#19 adding my availability times and learning goals
  collaboration/communication.md
  collaboration/learning_goals.md
Labels: documentation

#33 PR for Adding Name and README
  collaboration/communication.md
  collaboration/learning_goals.md
Labels: help wanted

#35 Domain study/student engagement
  0_domain_study/student_engagement.md
Labels: documentation

#49 Online platforms
  0_domain_study/0_online_platforms.md
Labels: good first issue
